// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oajelggqvpdfwjykepmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hamVsZ2dxdnBkZndqeWtlcG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MDM4ODUsImV4cCI6MjA1ODE3OTg4NX0.KfbR5I0KzQul0k2DHQEAXLlhk--l2-1D2tFkHhq0TeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);